version: "3.9"
services:
  phototime:
    image: mirsaes/phototime
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ${PHOTOTIME_DATA_DIR}
        target: /phototime-data
      - type: bind
        source: ${PHOTOTIME_REPO1_DIR}
        target: /phototime-repos/repo1
